### ISSUE TITLE
我报名的api接口问题

### ISSUE THREAD

**Issue by StellaSong12** [sysu-SAAD-project/Document#7]
希望返回格式类似海报墙页面

**Comment by TXZdream** [comment]
@xiaxzh 本周内完成处理，具体建议的方法如下：
1. 将原有海报墙所有字段全部返回
2. 若有新增内容，则在原有字段后追加新的字段
需要保证海报墙所有字段必须存在，而其余字段是否存在不作要求

**Comment by xiaxzh** [comment]
返回原有海报墙所有字段并添加studentId字段
studentId字段用途为：
当某用户为两个人报名同意活动时，用于具体区分

**Comment by TXZdream** [comment]
@SitingSong-SYSU 如果接口问题解决了就记得关闭一下issue
